config/routes.rb
Rails.application.routes.draw do

  root to: 'bread#show'

  resource :bread, controller: 'bread'

  resources :people
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bread.rb
class Bread
  include ActiveModel::Model
  include ActiveModel::Attributes
  include ActiveModel::Validations

  attribute :a, :integer, default: 2
  attribute :b, :integer, default: 3
  validates :a, :b, presence: true
  attr_writer :a2, :b2, :c2

  def sum
    a + b
  end

  def product
    a * b
  end

  def exponent
    a ** b
  end

  # memoization pattern
  # if @a2 
  #   @a2
  # else
  #   @a2 = a * a
  #
  def a2
    @a2 ||= a * a
  end

  def b2
    @b2 ||= b * b
  end

  def c2
    @c2 ||= a2 + b2
  end

  def c
    @c ||= Math.sqrt(c2)
  end

  def call
    return unless valid? 

    c
  end

  # class methods
  class << self
    def call(**)
      new(**).call
    end

    def proc
      ->(options) { new(**options).call }
    end
  end
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bread_controller.rb
class BreadController < ApplicationController
  before_action :set_bread

  def show
  end

  def create
    render :show
  end

  private

  def set_bread
    @bread = Bread.new(bread_params)
  end

  def bread_params
    params.fetch(:bread, {}).permit(:a, :b)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy!

    respond_to do |format|
      format.html { redirect_to people_path, status: :see_other, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.expect(person: [ :name ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bread/create.html.erb
<h1>Bread#create</h1>
<p>Find me in app/views/bread/create.html.erb</p>

app/views/bread/show.html.erb
<h1>Bread</h1>
<%= simple_form_for @bread, url: bread_path do |form| %>
  <%= form.input :a %>
  <%= form.input :b %>
  <%= form.submit 'Go' %>
<% end %>
<% if @bread.valid? %>
<ul>
  <li>a: <%= @bread.a %></li>
  <li>b: <%= @bread.b %></li>
  <li>sum: <%= @bread.sum %></li>
  <li>product: <%= @bread.product %></li>
  <li>exponent: <%= @bread.exponent %></li>
  <li>a2: <%= @bread.a2 %></li>
  <li>b2: <%= @bread.b2 %></li>
  <li>c2: <%= @bread.c2 %></li>
  <li>c: <%= @bread.c %></li>
</ul>
<% else %>
  Your missing something frank
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Sample Model App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body data-turbo="false">
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= simple_form_for(@person) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/people/_person.html.erb
<div id="<%= dom_id person %>">
  <p>
    <strong>Name:</strong>
    <%= person.name %>
  </p>

</div>

app/views/people/edit.html.erb
<% content_for :title, "Editing person" %>

<h1>Editing person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Show this person", @person %> |
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "People" %>

<h1>People</h1>

<div id="people">
  <% @people.each do |person| %>
    <%= render person %>
    <p>
      <%= link_to "Show this person", person %>
    </p>
  <% end %>
</div>

<%= link_to "New person", new_person_path %>

app/views/people/new.html.erb
<% content_for :title, "New person" %>

<h1>New person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @person %>

<div>
  <%= link_to "Edit this person", edit_person_path(@person) %> |
  <%= link_to "Back to people", people_path %>

  <%= button_to "Destroy this person", @person, method: :delete %>
</div>